### ISSUE TITLE
Authorization improvements

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2163] opened 2022-09-14 16:03 UTC
## Description
As an Admin / User, I want to have consistent authorization behavior for Global roles

## Acceptance criteria

- [ ] Registered user querying other's user authorization, returns `null` - should return an empty array `[ ]`
- [ ] Querying other self/other user privileges returns or doesn't `grant` privilege - the `grant` privilege, should not be returned when querying user's data
- [ ] Enable deletion for user-self
- [ ] Registered user not member of any community, cannot see the `verification_status` of the organizations - must have `read` privilege
- [ ] Global-Hubs-Admins, don't have `UPDATE_INNOVATION_FLOW` privilege (when not members of private hub) - must have that privilege  for Challenge / Opportunity
- [ ] Global-Hubs-Admins, don't have `CREATE_COMMENT` privilege on Aspect - must have the privilege for Hub / Challenge / Opportunity
- [ ] `UPDATE_CANVAS`  privilege is available on `Callout` and `Callout / Aspect` levels (for GA and GHA) - must be removed  for Hub / Challenge / Opportunity

For later:
- [ ] Registered users have `read` privileges to Hub and Challenge applications, when the hub is public - to be removed

**Comment by techsmyth** [comment] 2022-09-18 08:56
Duplicate of 2162

**Closed as completed by techsmyth** 2022-09-18 08:56 UTC
Labels: user story, server
