### ISSUE TITLE
BUG: Community not found for invitations

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Server#4214] opened 2024-07-05 14:43 UTC
**Describe the bug**
With user id: `70e6e81b-36d9-4feb-8547-fbb21b1dabc3` : `carlos@alkem.io`
Running this query: 
```
{
  me {
    communityInvitations{
      id
    }
  }
}
```
I get `Community not found for invitation 549a3a9e-ad47-454d-81b0-5e58e954db60`
```
"EntityNotFoundException: Community not found for invitation 549a3a9e-ad47-454d-81b0-5e58e954db60",
"    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:8:9)",
"    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)",
"    at MeService.getCommunityInvitationsForUser (/usr/src/app/dist/services/api/me/me.service.js:45:23)",
"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
"    at async target (/usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)",
"    at async Object.communityInvitations (/usr/src/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)"
```

Smells like bad data on acceptance but I think it requires investigation

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by bobbykolev** [comment] 2024-07-08 12:31
@Comoque1 I've also encountered issues with an empty Activity Log with error - comunity not found. It could be due to deletion of spaces/subspaces with pending invites but I didn't find the root cause.

Still reproducible with GA on acc for me:
_Community not found for invitation daf8c549-476c-460f-9421-a2f698df20fd_

**Comment by techsmyth** [comment] 2024-07-12 05:52
Moving to epic on data integrity + icebox: we first need to clean up orphaned data + then see what is happening.

**Comment by Comoque1** [comment] 2024-09-20 14:31
There is no such invitation on ACC env, anymore, so suspect the issue, would not be reproducible.
<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0x2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4f87ec7930430d9f50c4c2a79790b81e4bc687f/image.png" alt="image.png" />

**Closed as completed** 2024-09-20 14:31 UTC
Labels: bug, server
