### ISSUE TITLE
BUG: When user add "type" parameter in query for updatePreferenceOnHub error is thrown

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1793] opened 2022-03-10 11:39 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://test.alkem.io/graphql
2. Authenticate with GA
3. Perform the following mutation
```
mutation updatePreferenceOnHub($preferenceData: UpdateHubPreferenceInput!) {
  updatePreferenceOnHub(preferenceData: $preferenceData) {
    id
    value
    definition {
      valueType
      displayName
      type
    }
  }
}

```
```
{
  "preferenceData": {
    "hubID": "eco1",
    "type": "AUTHORIZATION_ANONYMOUS_READ_ACCESS",
    "value": "true"
  }
}
```

4. See error:` "message": "Enum \"UserPreferenceType\" cannot represent value: \"AuthorizationAnonymousReadAccess\"",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fd0b5b8b-7316-4b71-8fe3-5a1d6508375f)

**Expected behavior**
Mutation successfully executed and all data from the query is returned.

**Additional context**
For updating user preference works fine.

**Comment by techsmyth** [comment] 2022-03-10 13:00
Duplicate of #1792

**Closed as completed by techsmyth** 2022-03-10 13:00 UTC
Labels: bug, server
